Drawer icons
IssouProjects/Ubirb pull request #48
Opened 2018-01-02 20:21 UTC by TimotheeDurand

Ajout d'icônes dans le drawer

2018-01-02 21:53 UTC, AmosTrask approved these changes

2018-01-02 21:56 UTC, AmosTrask commented
Sur la forme je suis d'accord pour approve mais pas sur le fond (ou l'inverse)

2018-01-02 22:38 UTC, Raul6469 requested changes
Il y a des choses bizarres avec des commits antérieurs, je regarderai ça demain

2018-01-03 11:23 UTC, Raul6469 commented on gradle.properties
> +android.enableAapt2=false
C'est pour quoi ça déjà ?

2018-01-03 11:25 UTC, AmosTrask commented on gradle.properties
> +android.enableAapt2=false
ah, ça résout un bug de compilation

2018-01-03 11:25 UTC, Raul6469 commented on gradle.properties
> +android.enableAapt2=false
Ok, soit ^^

2018-01-03 11:47 UTC, Raul6469 approved these changes

2018-01-03 11:48 UTC, merged